GET localhost:8191/animals

###

GET localhost:8191/animals/arrived-on/2022-10-08

###

GET localhost:8191/animals/origin/germany

###

POST localhost:8191/animals
Content-Type: application/json

{
  "weight": 120,
  "origin": "Germany"
}

###

GET localhost:8191/parts

###

POST localhost:8191/parts
Content-Type: application/json

{
  "weight": 24,
  "name": "Throat",
  "animalNo": 1,
  "trayNo": 2
}

###

GET localhost:8191/products

###

POST localhost:8191/products
Content-Type: application/json

{
  "trayId": 2,
  "partNo": 1
}

###

GET localhost:8191/trays

###

POST localhost:8191/trays
Content-Type: application/json

{
  "maxWeightCapacity": 1500.0
}

