GET localhost:8080/animals/6

###

GET localhost:8080/animals/arrived-on/2022-11-21

###

GET localhost:8080/animals/origin/Croatia

###

POST localhost:8080/animals
Content-Type: application/json

{
  "weight": 120,
  "origin": "Poland"
}

###

GET localhost:8080/parts

###

POST localhost:8080/parts
Content-Type: application/json

{
  "weight": 24,
  "name": "Leg",
  "animalNo": 5,
  "trayId": 3
}

###

GET localhost:8080/products

###

GET localhost:8080/products/15

###

POST localhost:8080/products
Content-Type: application/json

{
  "trayId": 3,
  "partNo": [8,9]
}

###

GET localhost:8080/trays/3

###

POST localhost:8080/trays
Content-Type: application/json

{
  "maxWeightCapacity": 1500.0
}

###

GET localhost:8080/products/fromAnimal/5

###

GET localhost:8080/animals/involved/16

