// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Part.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

public interface EmptyPartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmptyPart)
    com.google.protobuf.MessageOrBuilder {
}
