// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

public interface FilterByDateRequestAnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FilterByDateRequestAnimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 year = 1;</code>
   * @return The year.
   */
  int getYear();

  /**
   * <code>int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 day = 3;</code>
   * @return The day.
   */
  int getDay();
}
