// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

/**
 * Protobuf type {@code FindByIdResponseAnimal}
 */
public final class FindByIdResponseAnimal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FindByIdResponseAnimal)
    FindByIdResponseAnimalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FindByIdResponseAnimal.newBuilder() to construct.
  private FindByIdResponseAnimal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FindByIdResponseAnimal() {
    animal_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FindByIdResponseAnimal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FindByIdResponseAnimal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              animal_ = new java.util.ArrayList<via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            animal_.add(
                input.readMessage(via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        animal_ = java.util.Collections.unmodifiableList(animal_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalOuterClass.internal_static_FindByIdResponseAnimal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalOuterClass.internal_static_FindByIdResponseAnimal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal.class, via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal.Builder.class);
  }

  public static final int ANIMAL_FIELD_NUMBER = 1;
  private java.util.List<via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage> animal_;
  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage> getAnimalList() {
    return animal_;
  }
  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessageOrBuilder> 
      getAnimalOrBuilderList() {
    return animal_;
  }
  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  @java.lang.Override
  public int getAnimalCount() {
    return animal_.size();
  }
  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  @java.lang.Override
  public via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage getAnimal(int index) {
    return animal_.get(index);
  }
  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  @java.lang.Override
  public via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessageOrBuilder getAnimalOrBuilder(
      int index) {
    return animal_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < animal_.size(); i++) {
      output.writeMessage(1, animal_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < animal_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, animal_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal)) {
      return super.equals(obj);
    }
    via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal other = (via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal) obj;

    if (!getAnimalList()
        .equals(other.getAnimalList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAnimalCount() > 0) {
      hash = (37 * hash) + ANIMAL_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FindByIdResponseAnimal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FindByIdResponseAnimal)
      via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalOuterClass.internal_static_FindByIdResponseAnimal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalOuterClass.internal_static_FindByIdResponseAnimal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal.class, via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal.Builder.class);
    }

    // Construct using via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnimalFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (animalBuilder_ == null) {
        animal_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        animalBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalOuterClass.internal_static_FindByIdResponseAnimal_descriptor;
    }

    @java.lang.Override
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal getDefaultInstanceForType() {
      return via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal build() {
      via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal buildPartial() {
      via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal result = new via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal(this);
      int from_bitField0_ = bitField0_;
      if (animalBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          animal_ = java.util.Collections.unmodifiableList(animal_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.animal_ = animal_;
      } else {
        result.animal_ = animalBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal) {
        return mergeFrom((via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal other) {
      if (other == via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal.getDefaultInstance()) return this;
      if (animalBuilder_ == null) {
        if (!other.animal_.isEmpty()) {
          if (animal_.isEmpty()) {
            animal_ = other.animal_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnimalIsMutable();
            animal_.addAll(other.animal_);
          }
          onChanged();
        }
      } else {
        if (!other.animal_.isEmpty()) {
          if (animalBuilder_.isEmpty()) {
            animalBuilder_.dispose();
            animalBuilder_ = null;
            animal_ = other.animal_;
            bitField0_ = (bitField0_ & ~0x00000001);
            animalBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnimalFieldBuilder() : null;
          } else {
            animalBuilder_.addAllMessages(other.animal_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage> animal_ =
      java.util.Collections.emptyList();
    private void ensureAnimalIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        animal_ = new java.util.ArrayList<via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage>(animal_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessageOrBuilder> animalBuilder_;

    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public java.util.List<via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage> getAnimalList() {
      if (animalBuilder_ == null) {
        return java.util.Collections.unmodifiableList(animal_);
      } else {
        return animalBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public int getAnimalCount() {
      if (animalBuilder_ == null) {
        return animal_.size();
      } else {
        return animalBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage getAnimal(int index) {
      if (animalBuilder_ == null) {
        return animal_.get(index);
      } else {
        return animalBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public Builder setAnimal(
        int index, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalIsMutable();
        animal_.set(index, value);
        onChanged();
      } else {
        animalBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public Builder setAnimal(
        int index, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder builderForValue) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        animal_.set(index, builderForValue.build());
        onChanged();
      } else {
        animalBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public Builder addAnimal(via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalIsMutable();
        animal_.add(value);
        onChanged();
      } else {
        animalBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public Builder addAnimal(
        int index, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalIsMutable();
        animal_.add(index, value);
        onChanged();
      } else {
        animalBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public Builder addAnimal(
        via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder builderForValue) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        animal_.add(builderForValue.build());
        onChanged();
      } else {
        animalBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public Builder addAnimal(
        int index, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder builderForValue) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        animal_.add(index, builderForValue.build());
        onChanged();
      } else {
        animalBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public Builder addAllAnimal(
        java.lang.Iterable<? extends via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage> values) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, animal_);
        onChanged();
      } else {
        animalBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public Builder clearAnimal() {
      if (animalBuilder_ == null) {
        animal_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        animalBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public Builder removeAnimal(int index) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        animal_.remove(index);
        onChanged();
      } else {
        animalBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder getAnimalBuilder(
        int index) {
      return getAnimalFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessageOrBuilder getAnimalOrBuilder(
        int index) {
      if (animalBuilder_ == null) {
        return animal_.get(index);  } else {
        return animalBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public java.util.List<? extends via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessageOrBuilder> 
         getAnimalOrBuilderList() {
      if (animalBuilder_ != null) {
        return animalBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(animal_);
      }
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder addAnimalBuilder() {
      return getAnimalFieldBuilder().addBuilder(
          via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder addAnimalBuilder(
        int index) {
      return getAnimalFieldBuilder().addBuilder(
          index, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .AnimalMessage animal = 1;</code>
     */
    public java.util.List<via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder> 
         getAnimalBuilderList() {
      return getAnimalFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessageOrBuilder> 
        getAnimalFieldBuilder() {
      if (animalBuilder_ == null) {
        animalBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage.Builder, via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessageOrBuilder>(
                animal_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        animal_ = null;
      }
      return animalBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FindByIdResponseAnimal)
  }

  // @@protoc_insertion_point(class_scope:FindByIdResponseAnimal)
  private static final via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal();
  }

  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FindByIdResponseAnimal>
      PARSER = new com.google.protobuf.AbstractParser<FindByIdResponseAnimal>() {
    @java.lang.Override
    public FindByIdResponseAnimal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FindByIdResponseAnimal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FindByIdResponseAnimal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FindByIdResponseAnimal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.animalregistrationsystem_sdj3.protobuf.FindByIdResponseAnimal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

