// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

public interface FindByIdResponseAnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindByIdResponseAnimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  java.util.List<via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage> 
      getAnimalList();
  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessage getAnimal(int index);
  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  int getAnimalCount();
  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  java.util.List<? extends via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessageOrBuilder> 
      getAnimalOrBuilderList();
  /**
   * <code>repeated .AnimalMessage animal = 1;</code>
   */
  via.sdj3.animalregistrationsystem_sdj3.protobuf.AnimalMessageOrBuilder getAnimalOrBuilder(
      int index);
}
