// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

public interface GetFromOriginRequestAnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetFromOriginRequestAnimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string origin = 1;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 1;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();
}
