// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

public interface GetMaxIdResponseAnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetMaxIdResponseAnimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 max_id = 1;</code>
   * @return The maxId.
   */
  long getMaxId();
}
