// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

public interface TrayDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrayData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double maxWeightCapacity = 1;</code>
   * @return The maxWeightCapacity.
   */
  double getMaxWeightCapacity();

  /**
   * <code>int64 trayId = 2;</code>
   * @return The trayId.
   */
  long getTrayId();
}
