// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

public interface TrayFindAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrayFindAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TrayData trays = 1;</code>
   */
  java.util.List<via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData> 
      getTraysList();
  /**
   * <code>repeated .TrayData trays = 1;</code>
   */
  via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData getTrays(int index);
  /**
   * <code>repeated .TrayData trays = 1;</code>
   */
  int getTraysCount();
  /**
   * <code>repeated .TrayData trays = 1;</code>
   */
  java.util.List<? extends via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayDataOrBuilder> 
      getTraysOrBuilderList();
  /**
   * <code>repeated .TrayData trays = 1;</code>
   */
  via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayDataOrBuilder getTraysOrBuilder(
      int index);
}
