// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

public interface TrayDeleteByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrayDeleteByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
