// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

/**
 * Protobuf type {@code TrayUpdateRequest}
 */
public final class TrayUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TrayUpdateRequest)
    TrayUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrayUpdateRequest.newBuilder() to construct.
  private TrayUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrayUpdateRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrayUpdateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrayUpdateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.Builder subBuilder = null;
            if (tray_ != null) {
              subBuilder = tray_.toBuilder();
            }
            tray_ = input.readMessage(via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tray_);
              tray_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayOuterClass.internal_static_TrayUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayOuterClass.internal_static_TrayUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest.class, via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest.Builder.class);
  }

  public static final int TRAY_FIELD_NUMBER = 1;
  private via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData tray_;
  /**
   * <code>.TrayData tray = 1;</code>
   * @return Whether the tray field is set.
   */
  @java.lang.Override
  public boolean hasTray() {
    return tray_ != null;
  }
  /**
   * <code>.TrayData tray = 1;</code>
   * @return The tray.
   */
  @java.lang.Override
  public via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData getTray() {
    return tray_ == null ? via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.getDefaultInstance() : tray_;
  }
  /**
   * <code>.TrayData tray = 1;</code>
   */
  @java.lang.Override
  public via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayDataOrBuilder getTrayOrBuilder() {
    return getTray();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tray_ != null) {
      output.writeMessage(1, getTray());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tray_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTray());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest)) {
      return super.equals(obj);
    }
    via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest other = (via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest) obj;

    if (hasTray() != other.hasTray()) return false;
    if (hasTray()) {
      if (!getTray()
          .equals(other.getTray())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTray()) {
      hash = (37 * hash) + TRAY_FIELD_NUMBER;
      hash = (53 * hash) + getTray().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TrayUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TrayUpdateRequest)
      via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayOuterClass.internal_static_TrayUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayOuterClass.internal_static_TrayUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest.class, via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest.Builder.class);
    }

    // Construct using via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (trayBuilder_ == null) {
        tray_ = null;
      } else {
        tray_ = null;
        trayBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayOuterClass.internal_static_TrayUpdateRequest_descriptor;
    }

    @java.lang.Override
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest getDefaultInstanceForType() {
      return via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest build() {
      via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest buildPartial() {
      via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest result = new via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest(this);
      if (trayBuilder_ == null) {
        result.tray_ = tray_;
      } else {
        result.tray_ = trayBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest) {
        return mergeFrom((via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest other) {
      if (other == via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest.getDefaultInstance()) return this;
      if (other.hasTray()) {
        mergeTray(other.getTray());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData tray_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData, via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.Builder, via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayDataOrBuilder> trayBuilder_;
    /**
     * <code>.TrayData tray = 1;</code>
     * @return Whether the tray field is set.
     */
    public boolean hasTray() {
      return trayBuilder_ != null || tray_ != null;
    }
    /**
     * <code>.TrayData tray = 1;</code>
     * @return The tray.
     */
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData getTray() {
      if (trayBuilder_ == null) {
        return tray_ == null ? via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.getDefaultInstance() : tray_;
      } else {
        return trayBuilder_.getMessage();
      }
    }
    /**
     * <code>.TrayData tray = 1;</code>
     */
    public Builder setTray(via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData value) {
      if (trayBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tray_ = value;
        onChanged();
      } else {
        trayBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.TrayData tray = 1;</code>
     */
    public Builder setTray(
        via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.Builder builderForValue) {
      if (trayBuilder_ == null) {
        tray_ = builderForValue.build();
        onChanged();
      } else {
        trayBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.TrayData tray = 1;</code>
     */
    public Builder mergeTray(via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData value) {
      if (trayBuilder_ == null) {
        if (tray_ != null) {
          tray_ =
            via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.newBuilder(tray_).mergeFrom(value).buildPartial();
        } else {
          tray_ = value;
        }
        onChanged();
      } else {
        trayBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.TrayData tray = 1;</code>
     */
    public Builder clearTray() {
      if (trayBuilder_ == null) {
        tray_ = null;
        onChanged();
      } else {
        tray_ = null;
        trayBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.TrayData tray = 1;</code>
     */
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.Builder getTrayBuilder() {
      
      onChanged();
      return getTrayFieldBuilder().getBuilder();
    }
    /**
     * <code>.TrayData tray = 1;</code>
     */
    public via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayDataOrBuilder getTrayOrBuilder() {
      if (trayBuilder_ != null) {
        return trayBuilder_.getMessageOrBuilder();
      } else {
        return tray_ == null ?
            via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.getDefaultInstance() : tray_;
      }
    }
    /**
     * <code>.TrayData tray = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData, via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.Builder, via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayDataOrBuilder> 
        getTrayFieldBuilder() {
      if (trayBuilder_ == null) {
        trayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData, via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData.Builder, via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayDataOrBuilder>(
                getTray(),
                getParentForChildren(),
                isClean());
        tray_ = null;
      }
      return trayBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TrayUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:TrayUpdateRequest)
  private static final via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest();
  }

  public static via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrayUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<TrayUpdateRequest>() {
    @java.lang.Override
    public TrayUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrayUpdateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrayUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrayUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

