// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package via.sdj3.animalregistrationsystem_sdj3.protobuf;

public interface TrayUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrayUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TrayData tray = 1;</code>
   * @return Whether the tray field is set.
   */
  boolean hasTray();
  /**
   * <code>.TrayData tray = 1;</code>
   * @return The tray.
   */
  via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayData getTray();
  /**
   * <code>.TrayData tray = 1;</code>
   */
  via.sdj3.animalregistrationsystem_sdj3.protobuf.TrayDataOrBuilder getTrayOrBuilder();
}
