// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.example;

public final class AnimalOuterClass {
  private AnimalOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllAnimals_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllAnimals_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FilterByDateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FilterByDateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMaxIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMaxIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetFromOriginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetFromOriginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Animal.proto\"o\n\021SaveAnimalRequest\022\014\n\004y" +
      "ear\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\013\n\003day\030\003 \001(\005\022\016\n" +
      "\006weight\030\004 \001(\001\022\020\n\010animalNo\030\005 \001(\003\022\016\n\006origi" +
      "n\030\006 \001(\t\"p\n\022SaveAnimalResponse\022\014\n\004year\030\001 " +
      "\001(\005\022\r\n\005month\030\002 \001(\005\022\013\n\003day\030\003 \001(\005\022\016\n\006weigh" +
      "t\030\004 \001(\001\022\020\n\010animalNo\030\005 \001(\003\022\016\n\006origin\030\006 \001(" +
      "\t\"k\n\rAnimalMessage\022\014\n\004year\030\001 \001(\005\022\r\n\005mont" +
      "h\030\002 \001(\005\022\013\n\003day\030\003 \001(\005\022\016\n\006weight\030\004 \001(\001\022\020\n\010" +
      "animalNo\030\005 \001(\003\022\016\n\006origin\030\006 \001(\t\"\035\n\017FindBy" +
      "IdRequest\022\n\n\002id\030\001 \001(\003\"q\n\023UpdateAnimalReq" +
      "uest\022\014\n\004year\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\013\n\003day" +
      "\030\003 \001(\005\022\016\n\006weight\030\004 \001(\001\022\020\n\010animalNo\030\005 \001(\003" +
      "\022\016\n\006origin\030\006 \001(\t\"r\n\024UpdateAnimalResponse" +
      "\022\014\n\004year\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\013\n\003day\030\003 \001" +
      "(\005\022\016\n\006weight\030\004 \001(\001\022\020\n\010animalNo\030\005 \001(\003\022\016\n\006" +
      "origin\030\006 \001(\t\"\037\n\021DeleteByIdRequest\022\n\n\002id\030" +
      "\001 \001(\003\"2\n\020FindByIdResponse\022\036\n\006animal\030\001 \003(" +
      "\0132\016.AnimalMessage\",\n\nAllAnimals\022\036\n\006anima" +
      "l\030\001 \003(\0132\016.AnimalMessage\"?\n\023FilterByDateR" +
      "equest\022\014\n\004year\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\013\n\003d" +
      "ay\030\003 \001(\005\"\"\n\020GetMaxIdResponse\022\016\n\006max_id\030\001" +
      " \001(\003\"&\n\024GetFromOriginRequest\022\016\n\006origin\030\001" +
      " \001(\t\"\007\n\005Empty2\217\003\n\006Animal\0225\n\nsaveAnimal\022\022" +
      ".SaveAnimalRequest\032\023.SaveAnimalResponse\022" +
      "/\n\010findById\022\020.FindByIdRequest\032\021.FindById" +
      "Response\022;\n\014updateAnimal\022\024.UpdateAnimalR" +
      "equest\032\025.UpdateAnimalResponse\022(\n\ndeleteB" +
      "yId\022\022.DeleteByIdRequest\032\006.Empty\022$\n\rfindA" +
      "llAnimal\022\006.Empty\032\013.AllAnimals\022/\n\nfindByD" +
      "ate\022\024.FilterByDateRequest\032\013.AllAnimals\022+" +
      "\n\016getMaxIdAnimal\022\006.Empty\032\021.GetMaxIdRespo" +
      "nse\0222\n\014findByOrigin\022\025.GetFromOriginReque" +
      "st\032\013.AllAnimalsB\017\n\013com.exampleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SaveAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SaveAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveAnimalRequest_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", "Weight", "AnimalNo", "Origin", });
    internal_static_SaveAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SaveAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveAnimalResponse_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", "Weight", "AnimalNo", "Origin", });
    internal_static_AnimalMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AnimalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalMessage_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", "Weight", "AnimalNo", "Origin", });
    internal_static_FindByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FindByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UpdateAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UpdateAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateAnimalRequest_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", "Weight", "AnimalNo", "Origin", });
    internal_static_UpdateAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UpdateAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateAnimalResponse_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", "Weight", "AnimalNo", "Origin", });
    internal_static_DeleteByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_DeleteByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_FindByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_FindByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindByIdResponse_descriptor,
        new java.lang.String[] { "Animal", });
    internal_static_AllAnimals_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_AllAnimals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllAnimals_descriptor,
        new java.lang.String[] { "Animal", });
    internal_static_FilterByDateRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_FilterByDateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FilterByDateRequest_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", });
    internal_static_GetMaxIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_GetMaxIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMaxIdResponse_descriptor,
        new java.lang.String[] { "MaxId", });
    internal_static_GetFromOriginRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GetFromOriginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetFromOriginRequest_descriptor,
        new java.lang.String[] { "Origin", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
