// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.example;

public interface GetMaxIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetMaxIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 max_id = 1;</code>
   * @return The maxId.
   */
  long getMaxId();
}
