// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package com.example;

public final class ProductOuterClass {
  private ProductOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ProductMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ProductMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_SaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_SaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_SaveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_SaveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_FindByRegNoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_FindByRegNoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_FindByRegNoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_FindByRegNoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ResponseFindAll_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ResponseFindAll_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_RequestDeleteByRegNo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_RequestDeleteByRegNo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ResponseGetMaxId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ResponseGetMaxId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rProduct.proto\022\007product\"H\n\016ProductMessa" +
      "ge\022\026\n\016registrationNo\030\001 \001(\003\022\016\n\006trayId\030\002 \001" +
      "(\003\022\016\n\006partNo\030\003 \001(\005\"E\n\013SaveRequest\022\026\n\016reg" +
      "istrationNo\030\001 \001(\003\022\016\n\006trayId\030\002 \001(\003\022\016\n\006par" +
      "tNo\030\003 \001(\005\"F\n\014SaveResponse\022\026\n\016registratio" +
      "nNo\030\001 \001(\003\022\016\n\006trayId\030\002 \001(\003\022\016\n\006partNo\030\003 \001(" +
      "\005\",\n\022FindByRegNoRequest\022\026\n\016registrationN" +
      "o\030\001 \001(\003\"M\n\023FindByRegNoResponse\022\026\n\016regist" +
      "rationNo\030\001 \001(\003\022\016\n\006trayId\030\002 \001(\003\022\016\n\006partNo" +
      "\030\003 \001(\005\"G\n\rUpdateRequest\022\026\n\016registrationN" +
      "o\030\001 \001(\003\022\016\n\006trayId\030\002 \001(\003\022\016\n\006partNo\030\003 \001(\005\"" +
      "H\n\016UpdateResponse\022\026\n\016registrationNo\030\001 \001(" +
      "\003\022\016\n\006trayId\030\002 \001(\003\022\016\n\006partNo\030\003 \001(\005\"@\n\017Res" +
      "ponseFindAll\022-\n\014product_list\030\001 \003(\0132\027.pro" +
      "duct.ProductMessage\"\'\n\024RequestDeleteByRe" +
      "gNo\022\017\n\007part_no\030\001 \001(\003\"\"\n\020ResponseGetMaxId" +
      "\022\016\n\006max_id\030\001 \001(\005\"\007\n\005Empty2\357\002\n\007Product\0223\n" +
      "\004save\022\024.product.SaveRequest\032\025.product.Sa" +
      "veResponse\022H\n\013findByRegNo\022\033.product.Find" +
      "ByRegNoRequest\032\034.product.FindByRegNoResp" +
      "onse\0229\n\006update\022\026.product.UpdateRequest\032\027" +
      ".product.UpdateResponse\022>\n\rdeleteByRegNo" +
      "\022\035.product.RequestDeleteByRegNo\032\016.produc" +
      "t.Empty\0223\n\007findAll\022\016.product.Empty\032\030.pro" +
      "duct.ResponseFindAll\0225\n\010getMaxId\022\016.produ" +
      "ct.Empty\032\031.product.ResponseGetMaxIdB\017\n\013c" +
      "om.exampleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_product_ProductMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_product_ProductMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ProductMessage_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_product_SaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_product_SaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_SaveRequest_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_product_SaveResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_product_SaveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_SaveResponse_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_product_FindByRegNoRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_product_FindByRegNoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_FindByRegNoRequest_descriptor,
        new java.lang.String[] { "RegistrationNo", });
    internal_static_product_FindByRegNoResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_product_FindByRegNoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_FindByRegNoResponse_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_product_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_product_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_UpdateRequest_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_product_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_product_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_UpdateResponse_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_product_ResponseFindAll_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_product_ResponseFindAll_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ResponseFindAll_descriptor,
        new java.lang.String[] { "ProductList", });
    internal_static_product_RequestDeleteByRegNo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_product_RequestDeleteByRegNo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_RequestDeleteByRegNo_descriptor,
        new java.lang.String[] { "PartNo", });
    internal_static_product_ResponseGetMaxId_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_product_ResponseGetMaxId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ResponseGetMaxId_descriptor,
        new java.lang.String[] { "MaxId", });
    internal_static_product_Empty_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_product_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
