// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package com.example;

public interface RequestDeleteByRegNoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.RequestDeleteByRegNo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 part_no = 1;</code>
   * @return The partNo.
   */
  long getPartNo();
}
