// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package com.example;

public interface ResponseGetMaxIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.ResponseGetMaxId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 max_id = 1;</code>
   * @return The maxId.
   */
  int getMaxId();
}
