// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Part.proto

package com.example.datapersistance.protobuf;

public interface AllPartsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AllParts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PartMessage parts = 1;</code>
   */
  java.util.List<com.example.datapersistance.protobuf.PartMessage> 
      getPartsList();
  /**
   * <code>repeated .PartMessage parts = 1;</code>
   */
  com.example.datapersistance.protobuf.PartMessage getParts(int index);
  /**
   * <code>repeated .PartMessage parts = 1;</code>
   */
  int getPartsCount();
  /**
   * <code>repeated .PartMessage parts = 1;</code>
   */
  java.util.List<? extends com.example.datapersistance.protobuf.PartMessageOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <code>repeated .PartMessage parts = 1;</code>
   */
  com.example.datapersistance.protobuf.PartMessageOrBuilder getPartsOrBuilder(
      int index);
}
