// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.example.datapersistance.protobuf;

public interface DeleteByIdRequestAnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteByIdRequestAnimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
