// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.example.datapersistance.protobuf;

public interface EmptyAnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmptyAnimal)
    com.google.protobuf.MessageOrBuilder {
}
