// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Part.proto

package com.example.datapersistance.protobuf;

public interface FIndByIdRequestPartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FIndByIdRequestPart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
