// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package com.example.datapersistance.protobuf;

public final class ProductOuterClass {
  private ProductOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveRequestProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveRequestProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveResponseProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveResponseProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindByRegNoRequestProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindByRegNoRequestProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindByRegNoResponseProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindByRegNoResponseProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateRequestProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateRequestProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateResponseProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateResponseProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseFindAllProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseFindAllProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestDeleteByRegNoProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestDeleteByRegNoProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseGetMaxIdProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseGetMaxIdProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyProduct_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rProduct.proto\"H\n\016ProductMessage\022\026\n\016reg" +
      "istrationNo\030\001 \001(\003\022\016\n\006trayId\030\002 \001(\003\022\016\n\006par" +
      "tNo\030\003 \003(\005\"L\n\022SaveRequestProduct\022\026\n\016regis" +
      "trationNo\030\001 \001(\003\022\016\n\006trayId\030\002 \001(\003\022\016\n\006partN" +
      "o\030\003 \003(\005\"M\n\023SaveResponseProduct\022\026\n\016regist" +
      "rationNo\030\001 \001(\003\022\016\n\006trayId\030\002 \001(\003\022\016\n\006partNo" +
      "\030\003 \003(\005\"3\n\031FindByRegNoRequestProduct\022\026\n\016r" +
      "egistrationNo\030\001 \001(\003\"T\n\032FindByRegNoRespon" +
      "seProduct\022\026\n\016registrationNo\030\001 \001(\003\022\016\n\006tra" +
      "yId\030\002 \001(\003\022\016\n\006partNo\030\003 \003(\005\"N\n\024UpdateReque" +
      "stProduct\022\026\n\016registrationNo\030\001 \001(\003\022\016\n\006tra" +
      "yId\030\002 \001(\003\022\016\n\006partNo\030\003 \003(\005\"O\n\025UpdateRespo" +
      "nseProduct\022\026\n\016registrationNo\030\001 \001(\003\022\016\n\006tr" +
      "ayId\030\002 \001(\003\022\016\n\006partNo\030\003 \003(\005\"?\n\026ResponseFi" +
      "ndAllProduct\022%\n\014product_list\030\001 \003(\0132\017.Pro" +
      "ductMessage\".\n\033RequestDeleteByRegNoProdu" +
      "ct\022\017\n\007part_no\030\001 \001(\003\")\n\027ResponseGetMaxIdP" +
      "roduct\022\016\n\006max_id\030\001 \001(\005\"\016\n\014EmptyProduct2\215" +
      "\003\n\007Product\0228\n\013saveProduct\022\023.SaveRequestP" +
      "roduct\032\024.SaveResponseProduct\022M\n\022findByRe" +
      "gNoProduct\022\032.FindByRegNoRequestProduct\032\033" +
      ".FindByRegNoResponseProduct\022>\n\rupdatePro" +
      "duct\022\025.UpdateRequestProduct\032\026.UpdateResp" +
      "onseProduct\022C\n\024deleteByRegNoProduct\022\034.Re" +
      "questDeleteByRegNoProduct\032\r.EmptyProduct" +
      "\0228\n\016findAllProduct\022\r.EmptyProduct\032\027.Resp" +
      "onseFindAllProduct\022:\n\017getMaxIdProduct\022\r." +
      "EmptyProduct\032\030.ResponseGetMaxIdProductB(" +
      "\n$com.example.datapersistance.protobufP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProductMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductMessage_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_SaveRequestProduct_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SaveRequestProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveRequestProduct_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_SaveResponseProduct_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SaveResponseProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveResponseProduct_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_FindByRegNoRequestProduct_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FindByRegNoRequestProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindByRegNoRequestProduct_descriptor,
        new java.lang.String[] { "RegistrationNo", });
    internal_static_FindByRegNoResponseProduct_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_FindByRegNoResponseProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindByRegNoResponseProduct_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_UpdateRequestProduct_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UpdateRequestProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateRequestProduct_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_UpdateResponseProduct_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_UpdateResponseProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateResponseProduct_descriptor,
        new java.lang.String[] { "RegistrationNo", "TrayId", "PartNo", });
    internal_static_ResponseFindAllProduct_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ResponseFindAllProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseFindAllProduct_descriptor,
        new java.lang.String[] { "ProductList", });
    internal_static_RequestDeleteByRegNoProduct_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_RequestDeleteByRegNoProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestDeleteByRegNoProduct_descriptor,
        new java.lang.String[] { "PartNo", });
    internal_static_ResponseGetMaxIdProduct_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ResponseGetMaxIdProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseGetMaxIdProduct_descriptor,
        new java.lang.String[] { "MaxId", });
    internal_static_EmptyProduct_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_EmptyProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyProduct_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
