// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.example.datapersistance.protobuf;

public interface ProductsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Products)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ProductMessageAnimal products = 1;</code>
   */
  java.util.List<com.example.datapersistance.protobuf.ProductMessageAnimal> 
      getProductsList();
  /**
   * <code>repeated .ProductMessageAnimal products = 1;</code>
   */
  com.example.datapersistance.protobuf.ProductMessageAnimal getProducts(int index);
  /**
   * <code>repeated .ProductMessageAnimal products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .ProductMessageAnimal products = 1;</code>
   */
  java.util.List<? extends com.example.datapersistance.protobuf.ProductMessageAnimalOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .ProductMessageAnimal products = 1;</code>
   */
  com.example.datapersistance.protobuf.ProductMessageAnimalOrBuilder getProductsOrBuilder(
      int index);
}
