// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package com.example.datapersistance.protobuf;

/**
 * Protobuf type {@code ResponseFindAllProduct}
 */
public final class ResponseFindAllProduct extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ResponseFindAllProduct)
    ResponseFindAllProductOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseFindAllProduct.newBuilder() to construct.
  private ResponseFindAllProduct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseFindAllProduct() {
    productList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResponseFindAllProduct();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseFindAllProduct(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              productList_ = new java.util.ArrayList<com.example.datapersistance.protobuf.ProductMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            productList_.add(
                input.readMessage(com.example.datapersistance.protobuf.ProductMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        productList_ = java.util.Collections.unmodifiableList(productList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.datapersistance.protobuf.ProductOuterClass.internal_static_ResponseFindAllProduct_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.datapersistance.protobuf.ProductOuterClass.internal_static_ResponseFindAllProduct_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.datapersistance.protobuf.ResponseFindAllProduct.class, com.example.datapersistance.protobuf.ResponseFindAllProduct.Builder.class);
  }

  public static final int PRODUCT_LIST_FIELD_NUMBER = 1;
  private java.util.List<com.example.datapersistance.protobuf.ProductMessage> productList_;
  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.datapersistance.protobuf.ProductMessage> getProductListList() {
    return productList_;
  }
  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.datapersistance.protobuf.ProductMessageOrBuilder> 
      getProductListOrBuilderList() {
    return productList_;
  }
  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  @java.lang.Override
  public int getProductListCount() {
    return productList_.size();
  }
  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  @java.lang.Override
  public com.example.datapersistance.protobuf.ProductMessage getProductList(int index) {
    return productList_.get(index);
  }
  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  @java.lang.Override
  public com.example.datapersistance.protobuf.ProductMessageOrBuilder getProductListOrBuilder(
      int index) {
    return productList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < productList_.size(); i++) {
      output.writeMessage(1, productList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < productList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, productList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.datapersistance.protobuf.ResponseFindAllProduct)) {
      return super.equals(obj);
    }
    com.example.datapersistance.protobuf.ResponseFindAllProduct other = (com.example.datapersistance.protobuf.ResponseFindAllProduct) obj;

    if (!getProductListList()
        .equals(other.getProductListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProductListCount() > 0) {
      hash = (37 * hash) + PRODUCT_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getProductListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.datapersistance.protobuf.ResponseFindAllProduct parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.datapersistance.protobuf.ResponseFindAllProduct prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ResponseFindAllProduct}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ResponseFindAllProduct)
      com.example.datapersistance.protobuf.ResponseFindAllProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.datapersistance.protobuf.ProductOuterClass.internal_static_ResponseFindAllProduct_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.datapersistance.protobuf.ProductOuterClass.internal_static_ResponseFindAllProduct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.datapersistance.protobuf.ResponseFindAllProduct.class, com.example.datapersistance.protobuf.ResponseFindAllProduct.Builder.class);
    }

    // Construct using com.example.datapersistance.protobuf.ResponseFindAllProduct.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProductListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (productListBuilder_ == null) {
        productList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        productListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.datapersistance.protobuf.ProductOuterClass.internal_static_ResponseFindAllProduct_descriptor;
    }

    @java.lang.Override
    public com.example.datapersistance.protobuf.ResponseFindAllProduct getDefaultInstanceForType() {
      return com.example.datapersistance.protobuf.ResponseFindAllProduct.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.datapersistance.protobuf.ResponseFindAllProduct build() {
      com.example.datapersistance.protobuf.ResponseFindAllProduct result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.datapersistance.protobuf.ResponseFindAllProduct buildPartial() {
      com.example.datapersistance.protobuf.ResponseFindAllProduct result = new com.example.datapersistance.protobuf.ResponseFindAllProduct(this);
      int from_bitField0_ = bitField0_;
      if (productListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          productList_ = java.util.Collections.unmodifiableList(productList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.productList_ = productList_;
      } else {
        result.productList_ = productListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.datapersistance.protobuf.ResponseFindAllProduct) {
        return mergeFrom((com.example.datapersistance.protobuf.ResponseFindAllProduct)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.datapersistance.protobuf.ResponseFindAllProduct other) {
      if (other == com.example.datapersistance.protobuf.ResponseFindAllProduct.getDefaultInstance()) return this;
      if (productListBuilder_ == null) {
        if (!other.productList_.isEmpty()) {
          if (productList_.isEmpty()) {
            productList_ = other.productList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProductListIsMutable();
            productList_.addAll(other.productList_);
          }
          onChanged();
        }
      } else {
        if (!other.productList_.isEmpty()) {
          if (productListBuilder_.isEmpty()) {
            productListBuilder_.dispose();
            productListBuilder_ = null;
            productList_ = other.productList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            productListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProductListFieldBuilder() : null;
          } else {
            productListBuilder_.addAllMessages(other.productList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.datapersistance.protobuf.ResponseFindAllProduct parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.datapersistance.protobuf.ResponseFindAllProduct) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.datapersistance.protobuf.ProductMessage> productList_ =
      java.util.Collections.emptyList();
    private void ensureProductListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        productList_ = new java.util.ArrayList<com.example.datapersistance.protobuf.ProductMessage>(productList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.datapersistance.protobuf.ProductMessage, com.example.datapersistance.protobuf.ProductMessage.Builder, com.example.datapersistance.protobuf.ProductMessageOrBuilder> productListBuilder_;

    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public java.util.List<com.example.datapersistance.protobuf.ProductMessage> getProductListList() {
      if (productListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(productList_);
      } else {
        return productListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public int getProductListCount() {
      if (productListBuilder_ == null) {
        return productList_.size();
      } else {
        return productListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public com.example.datapersistance.protobuf.ProductMessage getProductList(int index) {
      if (productListBuilder_ == null) {
        return productList_.get(index);
      } else {
        return productListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public Builder setProductList(
        int index, com.example.datapersistance.protobuf.ProductMessage value) {
      if (productListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductListIsMutable();
        productList_.set(index, value);
        onChanged();
      } else {
        productListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public Builder setProductList(
        int index, com.example.datapersistance.protobuf.ProductMessage.Builder builderForValue) {
      if (productListBuilder_ == null) {
        ensureProductListIsMutable();
        productList_.set(index, builderForValue.build());
        onChanged();
      } else {
        productListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public Builder addProductList(com.example.datapersistance.protobuf.ProductMessage value) {
      if (productListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductListIsMutable();
        productList_.add(value);
        onChanged();
      } else {
        productListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public Builder addProductList(
        int index, com.example.datapersistance.protobuf.ProductMessage value) {
      if (productListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductListIsMutable();
        productList_.add(index, value);
        onChanged();
      } else {
        productListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public Builder addProductList(
        com.example.datapersistance.protobuf.ProductMessage.Builder builderForValue) {
      if (productListBuilder_ == null) {
        ensureProductListIsMutable();
        productList_.add(builderForValue.build());
        onChanged();
      } else {
        productListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public Builder addProductList(
        int index, com.example.datapersistance.protobuf.ProductMessage.Builder builderForValue) {
      if (productListBuilder_ == null) {
        ensureProductListIsMutable();
        productList_.add(index, builderForValue.build());
        onChanged();
      } else {
        productListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public Builder addAllProductList(
        java.lang.Iterable<? extends com.example.datapersistance.protobuf.ProductMessage> values) {
      if (productListBuilder_ == null) {
        ensureProductListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productList_);
        onChanged();
      } else {
        productListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public Builder clearProductList() {
      if (productListBuilder_ == null) {
        productList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        productListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public Builder removeProductList(int index) {
      if (productListBuilder_ == null) {
        ensureProductListIsMutable();
        productList_.remove(index);
        onChanged();
      } else {
        productListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public com.example.datapersistance.protobuf.ProductMessage.Builder getProductListBuilder(
        int index) {
      return getProductListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public com.example.datapersistance.protobuf.ProductMessageOrBuilder getProductListOrBuilder(
        int index) {
      if (productListBuilder_ == null) {
        return productList_.get(index);  } else {
        return productListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public java.util.List<? extends com.example.datapersistance.protobuf.ProductMessageOrBuilder> 
         getProductListOrBuilderList() {
      if (productListBuilder_ != null) {
        return productListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(productList_);
      }
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public com.example.datapersistance.protobuf.ProductMessage.Builder addProductListBuilder() {
      return getProductListFieldBuilder().addBuilder(
          com.example.datapersistance.protobuf.ProductMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public com.example.datapersistance.protobuf.ProductMessage.Builder addProductListBuilder(
        int index) {
      return getProductListFieldBuilder().addBuilder(
          index, com.example.datapersistance.protobuf.ProductMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .ProductMessage product_list = 1;</code>
     */
    public java.util.List<com.example.datapersistance.protobuf.ProductMessage.Builder> 
         getProductListBuilderList() {
      return getProductListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.datapersistance.protobuf.ProductMessage, com.example.datapersistance.protobuf.ProductMessage.Builder, com.example.datapersistance.protobuf.ProductMessageOrBuilder> 
        getProductListFieldBuilder() {
      if (productListBuilder_ == null) {
        productListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.datapersistance.protobuf.ProductMessage, com.example.datapersistance.protobuf.ProductMessage.Builder, com.example.datapersistance.protobuf.ProductMessageOrBuilder>(
                productList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        productList_ = null;
      }
      return productListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ResponseFindAllProduct)
  }

  // @@protoc_insertion_point(class_scope:ResponseFindAllProduct)
  private static final com.example.datapersistance.protobuf.ResponseFindAllProduct DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.datapersistance.protobuf.ResponseFindAllProduct();
  }

  public static com.example.datapersistance.protobuf.ResponseFindAllProduct getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseFindAllProduct>
      PARSER = new com.google.protobuf.AbstractParser<ResponseFindAllProduct>() {
    @java.lang.Override
    public ResponseFindAllProduct parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseFindAllProduct(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseFindAllProduct> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseFindAllProduct> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.datapersistance.protobuf.ResponseFindAllProduct getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

