// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package com.example.datapersistance.protobuf;

public interface ResponseFindAllProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseFindAllProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  java.util.List<com.example.datapersistance.protobuf.ProductMessage> 
      getProductListList();
  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  com.example.datapersistance.protobuf.ProductMessage getProductList(int index);
  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  int getProductListCount();
  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  java.util.List<? extends com.example.datapersistance.protobuf.ProductMessageOrBuilder> 
      getProductListOrBuilderList();
  /**
   * <code>repeated .ProductMessage product_list = 1;</code>
   */
  com.example.datapersistance.protobuf.ProductMessageOrBuilder getProductListOrBuilder(
      int index);
}
