// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package com.example.datapersistance.protobuf;

public interface TrayFindByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrayFindByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
