// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package com.example.datapersistance.protobuf;

public interface TrayUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrayUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TrayData tray = 1;</code>
   * @return Whether the tray field is set.
   */
  boolean hasTray();
  /**
   * <code>.TrayData tray = 1;</code>
   * @return The tray.
   */
  com.example.datapersistance.protobuf.TrayData getTray();
  /**
   * <code>.TrayData tray = 1;</code>
   */
  com.example.datapersistance.protobuf.TrayDataOrBuilder getTrayOrBuilder();
}
