// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package com.example.datapersistance.protobuf;

public interface TrayEmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrayEmpty)
    com.google.protobuf.MessageOrBuilder {
}
